-- Mapa de Grupos Empresariales Paraguay — seed de datos
-- Ejecutar DESPUÉS de supabase_schema.sql, en el SQL Editor de Supabase.
-- Usa dollar-quoting ($txt$...$txt$) en vez de comillas simples para evitar
-- errores de escape con apóstrofes reales del texto (Chaco'i, Hellmann's,
-- Jack Daniel's, Watt's, etc.) — no hace falta duplicar comillas a mano.

-- =========================================================================
-- market_groups (17 grupos familiares)
-- =========================================================================
insert into market_groups (name, rubro, size, empleados, facturacion, liderazgo, nota_rrhh, sort_order) values
($txt$Grupo Azeta (Zuccolillo)$txt$, $txt$Diversificado$txt$, 98,
 $txt$N/D (conglomerado grande, sin cifra pública consolidada; 82% de favorabilidad en certificación Great Place to Work vs. 66% de promedio de mercado)$txt$,
 $txt$N/D como facturación oficial — referencia indirecta de escala: pagó G. 461.724 millones (~US$62,8M) en impuestos en 2024, y ya acumulaba ~US$57,8M en impuestos al 23/09/2025 (Diario HOY / La Nación)$txt$,
 $txt$Familia Zuccolillo — Aldo Zuccolillo (fundador ABC Color), Pedro Zuccolillo$txt$,
 $txt$En expansión activa: compró Biggie, Sueñolar y Canal PRO, y negocia Tigo Money — es de los grupos con más movimiento de M&A del país ahora mismo, lo que suele anticipar demanda de gerencias nuevas.$txt$, 1),
($txt$Grupo Cartes / Cartes Montaña$txt$, $txt$Diversificado$txt$, 78,
 $txt$~6.300 (2024, entre Sarah Cartes Holding y Cartes Montaña — IPS)$txt$,
 $txt$N/D$txt$,
 $txt$Horacio Cartes (fundador); Juan Pablo, Sofía y María Sol Cartes Montaña (nueva generación); Sarah Cartes (hermana) y José Ortiz (reestructuración financiera)$txt$,
 $txt$⚠️ Verificar SIEMPRE la razón social exacta antes de contratar o facturar: tras las sanciones OFAC (2023-2025) y una donación en vida, la mayoría de las empresas pasaron de Horacio Cartes a sus hijos (Cartes Montaña) o a su hermana Sarah Cartes. "Grupo Cartes" como marca ya no refleja quién controla legalmente cada firma.$txt$, 2),
($txt$Grupo Vierci (A.J. Vierci)$txt$, $txt$Diversificado$txt$, 99,
 $txt$~18.600 colaboradores directos (+5.000 en la división fast food)$txt$,
 $txt$Aportó ~G. 327.000 millones en impuestos en 2023 (~US$42M) — Forbes Paraguay$txt$,
 $txt$Antonio J. Vierci (fundador, presidente) — Forbes Selection y Personaje del Año 2025 (Revista PLUS)$txt$,
 $txt$El conglomerado privado más grande y diversificado del país por prensa reciente. Prensa confirma 30-40+ empresas en el portafolio, aunque muchas subsidiarias/SPV no se nombran individualmente. Actividad de M&A constante: 44% de Banco GNB (2023), fusión BDP con CCU (2024), franquicia máster de Subway para España/Portugal (2025, +450 locales en 10 años). Motor casi permanente de búsquedas gerenciales por su ritmo de expansión.$txt$, 3),
($txt$Grupo Zapag$txt$, $txt$Combustibles/Energía$txt$, 97,
 $txt$N/D$txt$,
 $txt$Paracel: inversión de US$ 4.000 millones (mayor inversión privada de la historia del país)$txt$,
 $txt$Familia Zapag$txt$,
 $txt$Opera además en Uruguay, Bolivia y Argentina (Copetrol, Axion Uruguay). Paracel (planta de celulosa de 1,8M ton/año, ampliable a 5M, en Paso Horqueta, Concepción, con casi 200.000 hectáreas forestales propias) estuvo en pausa constructiva y en mayo de 2026 recién inició obras de infraestructura del polo industrial — producción de celulosa proyectada recién para 2030. Activos acumulados +US$1.400M, financiamiento BID Invest de hasta US$165M, y estimación de 7.000 empleos directos e indirectos cuando esté operativa — uno de los proyectos industriales más grandes de la historia del país, pero con cronograma más largo del previsto inicialmente.$txt$, 4),
($txt$Grupo Garden$txt$, $txt$Automotor$txt$, 58,
 $txt$Más de 1.300 colaboradores (Revista PLUS, oct. 2025)$txt$,
 $txt$N/D$txt$,
 $txt$Familia Garden$txt$,
 $txt$⚠️ Corrección de dato: este grupo NO es concesionario de Mercedes-Benz (esa marca la representa Grupo Cóndor en Paraguay hace 60+ años) — se corrigió el error. El portafolio real de Garden es multimarca de volumen: KIA (líder de ventas del país 14 años consecutivos), Chevrolet, Mazda, Nissan, Fiat, y el grupo Jeep/Dodge/RAM/Chrysler/Mopar. Fundado en 1985 en Ciudad del Este. Elegido mejor concesionaria de Paraguay dos años consecutivos (Revista PLUS, 2025).$txt$, 5),
($txt$Grupo Harrison$txt$, $txt$Salud/Medios$txt$, 90,
 $txt$N/D$txt$,
 $txt$~US$ 500 millones/año (Forbes Paraguay)$txt$,
 $txt$Robert Harrison y Aldo Harrison (hermanos, 2da/3ra generación); Óscar Harrison (padre, fundador)$txt$,
 $txt$Muy activo en M&A reciente: compró Grupo Migone (2024), Asepasa y Solbet — el foco está en consolidar salud/seguros y ahora entretenimiento digital, sectores donde suelen abrir búsquedas gerenciales tras cada adquisición.$txt$, 6),
($txt$Grupo Bogarín$txt$, $txt$Industria/Construcción$txt$, 88,
 $txt$N/D a nivel grupo (una sola de sus empresas, Yguazú Cementos, reporta ~150 empleados según bases de datos corporativas — cifra no oficial)$txt$,
 $txt$N/D a nivel grupo (Yguazú Cementos sola: ~US$14,5M estimados por bases de datos corporativas — cifra no oficial y no representa al grupo completo)$txt$,
 $txt$Familia Bogarín (José R. Bogarín, fundador, fallecido)$txt$,
 $txt$Yguazú Cementos abastece ~40% del consumo nacional de cemento — posición dominante en un rubro con poca rotación de talento senior, útil para búsquedas de nicho. ⚠️ Verificar composición societaria: en 2020 la argentina Loma Negra (Camargo Correa) vendió su 51% y la empresa pasó a ser 100% de capital paraguayo — la prensa describe al comprador como "un grupo vinculado a Concret-Mix (Bogarín)" sin confirmar si es el mismo Bogarín u otro capital paraguayo asociado.$txt$, 7),
($txt$Grupo Riquelme$txt$, $txt$Consumo Masivo$txt$, 70,
 $txt$~3.000 colaboradores$txt$,
 $txt$N/D$txt$,
 $txt$Jorge Riquelme (director); Marta, Stella y María Elena Riquelme; Dra. Licy Yanes de Riquelme (presidenta); fundador Blas N. Riquelme$txt$,
 $txt$Empresa familiar con sucesión de 2da generación ya consolidada y gestión compartida entre hermanos — cultura de decisión colegiada, relevante para procesos de gerencia general.$txt$, 8),
($txt$Grupo Pettengill$txt$, $txt$Agroindustria/Construcción$txt$, 68,
 $txt$~2.000+ a nivel grupo — solo Frigorífico Guaraní ya suma ~1.300 (600 directos en planta cárnica) más el personal de los consorcios viales y constructoras$txt$,
 $txt$N/D$txt$,
 $txt$Luis Alberto Pettengill Vacca (senador, fundador junto a José R. Bogarín); Juan Carlos y Blanca María Pettengill$txt$,
 $txt$⚠️ Alta exposición a contratos estatales y cobertura de prensa por conflictos de interés — recomendable due diligence reputacional antes de procesos con clientes sensibles a este tipo de vínculos.$txt$, 9),
($txt$Grupo Ortega$txt$, $txt$Combustibles/Energía$txt$, 62,
 $txt$N/D$txt$,
 $txt$N/D como facturación oficial — referencia indirecta: Raízen (JV de Shell y Cosan) pagó US$130M por el 50% de Barcos & Rodados en 2021 (US$40M al cierre + US$90M en 5 cuotas anuales), valuando la operación completa por encima de ese monto$txt$,
 $txt$Familia Ortega (empresa familiar) — Luis y Miguel Ortega Echeverría continúan en el directorio tras la venta del 50% a Raízen$txt$,
 $txt$Red de 350+ estaciones de servicio y 150 tiendas de conveniencia Rapidito, una de las mayores del país — ya completó la transición de marca a Shell vía joint venture con Raízen (2021), proceso que generó integración operativa con el nuevo socio.$txt$, 10),
($txt$Grupo Martín Martín$txt$, $txt$Combustibles/Energía$txt$, 52,
 $txt$N/D a nivel grupo (Fuelpar sola reporta ~30 empleados según bases de datos corporativas — cifra no oficial)$txt$,
 $txt$N/D$txt$,
 $txt$Familia Martín Martín$txt$,
 $txt$Fuerte presencia regional en la zona norte del país — perfil interesante para búsquedas fuera de Asunción/Gran Asunción.$txt$, 11),
($txt$Grupo Luminotecnia$txt$, $txt$Industria/Construcción$txt$, 52,
 $txt$~740 colaboradores$txt$,
 $txt$N/D$txt$,
 $txt$Plana directiva familiar (fundado en 1981)$txt$,
 $txt$🏆 Top of Mind #1 en "Casa de Electricidad" 3 años consecutivos. 💚 Certificado Great Place to Work — Top 13 en organizaciones grandes y Top 8 para Centennials en Paraguay (2024). Cultura empleadora muy documentada y positiva, poco frecuente encontrar tanta data pública de clima laboral.$txt$, 12),
($txt$Grupo Alkan (Hoeckle)$txt$, $txt$Combustibles/Energía$txt$, 66,
 $txt$N/D a nivel grupo — solo AZPA (Azucarera Paraguaya) ya emplea 1.000+ colaboradores directos y genera empleo indirecto para ~100.000 personas vía tercerizados y productores cañeros asociados$txt$,
 $txt$Grupo Alkan (negocio de combustibles): ventas anuales superiores a US$ 250 millones. Otras empresas de la familia Hoeckle (AZPA, Envapar, Navesur) no tienen facturación consolidada pública — no están incluidas en esa cifra$txt$,
 $txt$Familia Hoeckle — Conrado Hoeckle (ex asesor económico de la Presidencia); Emanuelle Hoeckle Alfaro (presidenta, nueva generación); Raúl Joaquín Hoeckle Ritter (representante legal de Envapar); Stephanie Hoeckle (directora del proyecto TOSA)$txt$,
 $txt$⚠️ Fuerte exposición política y mediática: Conrado Hoeckle fue asesor económico presidencial y sus empresas (Monte Alegre, TOSA) han sido señaladas en varias notas de prensa por contratos estatales adjudicados sin competencia — due diligence reputacional recomendable antes de procesos con clientes sensibles a este tipo de vínculos. En 2023 la familia recompró el 40% de Alkan que estaba en manos del trader suizo Gunvor. El grupo es más diversificado de lo que sugiere el negocio de combustibles: azúcar (AZPA, exportador líder de azúcar orgánica), envases plásticos (Envapar) y transporte fluvial (Navesur).$txt$, 13),
($txt$Grupo Toyotoshi$txt$, $txt$Automotor$txt$, 66,
 $txt$~1.000+ colaboradores directos (683 solo entre Toyotoshi y AutoMarket)$txt$,
 $txt$N/D$txt$,
 $txt$Marcelo Toyotoshi (presidente, 2da generación); Patricia Toyotoshi (directora); fundador Naoyuki Toyotoshi (1969)$txt$,
 $txt$💚 Certificado Great Place to Work (96% de favorabilidad vs. 66% promedio de mercado) — uno de los datos de clima laboral más sólidos que encontré en todo este mapeo. Cultura mixta japonesa-paraguaya explícitamente gestionada como valor de marca empleadora. También tiene 5 empresas concesionarias de Toyota y Lexus en Canadá.$txt$, 14),
($txt$Distribuidora Gloria$txt$, $txt$Retail$txt$, 48,
 $txt$N/D$txt$, $txt$N/D$txt$,
 $txt$Iván Dumot (director ejecutivo; también preside el Centro de Importadores del Paraguay — CIP)$txt$,
 $txt$Distribuidora local fundada en 1988, hoy con torre corporativa propia en Asunción.$txt$, 15),
($txt$Grupo Gorostiaga$txt$, $txt$Automotor$txt$, 44,
 $txt$N/D (estimaciones no oficiales entre 11 y 50 según directorios corporativos — rango demasiado amplio para citar como cifra)$txt$,
 $txt$N/D$txt$,
 $txt$Familia Gorostiaga — Rodrigo Gorostiaga Jiménez Gaona, Paloma Gorostiaga Zavala y Catalina Gorostiaga (representantes legales, registro de contrataciones públicas)$txt$,
 $txt$Grupo más pequeño y menos cubierto por prensa financiera. Opera 6 sucursales (Asunción, Santa Rita, Hernandarias, Ciudad del Este) con ~26 años de trayectoria — datos financieros a completar con fuentes propias de Incentiva si hay relación comercial directa.$txt$, 16),
($txt$Grupo Cogorno$txt$, $txt$Diversificado$txt$, 75,
 $txt$8.000+ empleos directos a nivel grupo (Shopping China solo emplea a 1.800 personas en sus 3 sucursales)$txt$,
 $txt$N/D consolidado — dato de contexto: el canal e-commerce ya representa ~30% de la facturación de Shopping China$txt$,
 $txt$Familia Cogorno — Felipe Cogorno (inmigrante italiano, fundador en 1933); familia Cogorno Álvarez (control accionario actual)$txt$,
 $txt$Grupo familiar de 90+ años que pasó de retail de importados fronterizo a mayorista cash & carry, y desde 2020 se diversificó agresivamente a banca (tomó el control de Interfisa) y en 2025 a seguros (compra de Río Seguros) — expansión activa que suele anticipar demanda de gerencias nuevas en las áreas recién adquiridas.$txt$, 17);

-- =========================================================================
-- market_companies (124 empresas de grupos)
-- =========================================================================
insert into market_companies (group_id, nombre, rubro, badge, sort_order) values
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$ABC Color / Editorial Azeta$txt$, $txt$Medios$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Mercurio SA (industria gráfica)$txt$, $txt$Industria$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Núcleo SACI (opera la marca Personal)$txt$, $txt$Telecom$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Banco Atlas (en fusión con Familiar)$txt$, $txt$Financiero$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Tigo Money (en proceso de adquisición)$txt$, $txt$Fintech$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Biggie (50%, tiendas de cercanía) + Biggie Farma$txt$, $txt$Retail$txt$, null, 6),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Sueñolar (50%, colchones y muebles)$txt$, $txt$Industria/Retail$txt$, null, 7),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Shoppings Mariscal, Mariano y del Sol$txt$, $txt$Retail/Inmobiliario$txt$, null, 8),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Inmobiliaria del Este$txt$, $txt$Inmobiliario$txt$, null, 9),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Vanguardia Agronegocios$txt$, $txt$Agro$txt$, null, 10),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Esur (energía)$txt$, $txt$Energía$txt$, null, 11),
((select id from market_groups where name=$txt$Grupo Azeta (Zuccolillo)$txt$), $txt$Nueva Americana (retail)$txt$, $txt$Retail$txt$, null, 12),

((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$Banco Basa$txt$, $txt$Financiero$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$Veneto SA (nuevo eje financiero del grupo)$txt$, $txt$Financiero$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$Frigorífico Chajhá$txt$, $txt$Agroindustria$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$Cadena Farmacenter$txt$, $txt$Farma/Retail$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$Cementos Concepción$txt$, $txt$Cemento$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$QSR SA (franquicias Donvito / Sbarro)$txt$, $txt$Gastronomía$txt$, null, 6),
((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$Hoteles Sheraton, Four Points y Aloft (Asunción / CDE)$txt$, $txt$Hotelería$txt$, null, 7),
((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$Red de sociedades agroganaderas y forestales (Ganadera Las Pampas, Ganadera Sofía, Agroforestal del Amambay y otras)$txt$, $txt$Agro$txt$, null, 8),
((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$Jiménez Gaona y Lima (construcciones)$txt$, $txt$Construcción$txt$, null, 9),
((select id from market_groups where name=$txt$Grupo Cartes / Cartes Montaña$txt$), $txt$Tabacalera del Este / Tabesa (Cartes vendió sus acciones a Palermo SA por más de US$120M en marzo 2023, hoy fuera del grupo)$txt$, $txt$Tabaco$txt$, null, 10),

((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$AJ SA (empresa madre: alimentos, bebidas, cuidado personal y del hogar)$txt$, $txt$Industria/Alimentos$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$BDP – Bebidas del Paraguay (fusión con CCU: Pepsi, Heineken, Watt's y +30 marcas; vía AV SA también distribuye los snacks PepsiCo Lay's, Doritos, Cheetos y Quaker)$txt$, $txt$Bebidas$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Banco GNB Paraguay (44% de participación)$txt$, $txt$Financiero$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Supermercados Stock y Superseis / Delimarket (Retail SA)$txt$, $txt$Retail$txt$, 'gptw', 4),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Burger King y Popeyes (Adiser LAC) — Paraguay, Uruguay, Brasil, Panamá, EE.UU.$txt$, $txt$Gastronomía$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Subway (franquicia máster Paraguay, Uruguay y ahora España/Portugal)$txt$, $txt$Gastronomía$txt$, null, 6),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Perfumerías Champs Élysées (12 locales) — Carolina Herrera, Rabanne, O Boticario, próx. Tom Ford$txt$, $txt$Retail$txt$, 'gptw', 7),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Distribución de espirituosas: Jack Daniel's, Licor 43, Pisco Mistral, vinos Misiones de Rengo/La Celia$txt$, $txt$Bebidas alcohólicas importadas$txt$, null, 8),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Última Hora, Diario Extra, Telefuturo, NPy, La Tele$txt$, $txt$Medios$txt$, null, 9),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Radio Monumental, Radio Urbana, Radio Chaco Boreal, Estación 40$txt$, $txt$Medios$txt$, null, 10),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Paraguay.com / Clasipar.com$txt$, $txt$Medios digitales$txt$, null, 11),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Yerbatera Campesino / Embutidos Franz$txt$, $txt$Industria/Alimentos$txt$, null, 12),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Compañía de Desarrollo Agropecuario (miles de hectáreas de ganadería)$txt$, $txt$Agro$txt$, null, 13),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Cartera inmobiliaria propia (gestión de inmuebles del grupo)$txt$, $txt$Inmobiliario$txt$, null, 14),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$GDN Uruguay (TaTa, Farmacia San Roque, BAS, MultiAhorro, Frontoy)$txt$, $txt$Retail internacional$txt$, null, 15),
((select id from market_groups where name=$txt$Grupo Vierci (A.J. Vierci)$txt$), $txt$Etosha (alimentos plant-based, Uruguay)$txt$, $txt$Industria/Alimentos$txt$, null, 16),

((select id from market_groups where name=$txt$Grupo Zapag$txt$), $txt$Copetrol (Paraguay, Bolivia, Argentina)$txt$, $txt$Combustibles$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Zapag$txt$), $txt$Nextar (ex-Petrobras Paraguay)$txt$, $txt$Combustibles$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Zapag$txt$), $txt$Axion Uruguay$txt$, $txt$Combustibles$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Zapag$txt$), $txt$Paracel (planta de celulosa, US$4.000M de inversión)$txt$, $txt$Forestal/Industria$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Zapag$txt$), $txt$Cargo Line Paraguay (logística fluvial)$txt$, $txt$Logística$txt$, null, 5),

((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$KIA (representante exclusivo desde 2002, líder de ventas 14 años consecutivos)$txt$, $txt$Automotor$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$Tema Automotores S.A. (Chevrolet, desde 1998)$txt$, $txt$Automotor$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$Mazda (desde 2008)$txt$, $txt$Automotor$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$Grupo Chrysler: Jeep, Dodge, RAM, Chrysler, SRT y Mopar (desde 2010)$txt$, $txt$Automotor$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$MINI y BMW Motorrad (desde 2011)$txt$, $txt$Automotor$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$Cuevas Hermanos S.A. (Nissan, desde 2017)$txt$, $txt$Automotor$txt$, null, 6),
((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$Fiat$txt$, $txt$Automotor$txt$, null, 7),
((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$Lubricantes$txt$, $txt$Combustibles$txt$, null, 8),
((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$Seguros (correduría vinculada)$txt$, $txt$Seguros$txt$, null, 9),
((select id from market_groups where name=$txt$Grupo Garden$txt$), $txt$Repuestos y talleres mecánicos$txt$, $txt$Automotor$txt$, null, 10),

((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$Sanatorio Británico$txt$, $txt$Salud$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$Grupo Migone (sanatorio + seguro + NLPharma + limpieza + catering)$txt$, $txt$Salud$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$Sanatorio y Seguro Santa Clara$txt$, $txt$Salud$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$Quimfa (laboratorio farmacéutico)$txt$, $txt$Farma$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$FarmaOliva (cadena de farmacias)$txt$, $txt$Farma$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$La Policlínica (distribuidora farmacéutica)$txt$, $txt$Farma$txt$, null, 6),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$Industria Gráfica Novel$txt$, $txt$Industria$txt$, null, 7),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$Aseguradora Yacyretá / Asepasa$txt$, $txt$Seguros$txt$, null, 8),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$TecnoParaguay (dealer Claro)$txt$, $txt$Telecom$txt$, null, 9),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$Megacadena (Canal 100, Canal PRO, Radio Latina, Radio 1° de Marzo, Radio Mariscal Estigarribia)$txt$, $txt$Medios$txt$, null, 10),
((select id from market_groups where name=$txt$Grupo Harrison$txt$), $txt$Solbet (juego online)$txt$, $txt$Entretenimiento digital$txt$, null, 11),

((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Automotor (Hyundai, Maserati, Geely, Isuzu)$txt$, $txt$Automotor$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Pluscar (compraventa de vehículos)$txt$, $txt$Automotor$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Concret Mix$txt$, $txt$Construcción$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Construshopping$txt$, $txt$Construcción$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Yguazú Cementos$txt$, $txt$Cemento$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Parglass (fábrica de envases de vidrio)$txt$, $txt$Industria$txt$, null, 6),
((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Multiplaza (shopping)$txt$, $txt$Retail$txt$, null, 7),
((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Integral Trading (estaciones de servicio)$txt$, $txt$Combustibles$txt$, null, 8),
((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Puerto privado San José$txt$, $txt$Logística$txt$, null, 9),
((select id from market_groups where name=$txt$Grupo Bogarín$txt$), $txt$Empresas ganaderas del grupo$txt$, $txt$Agro$txt$, null, 10),

((select id from market_groups where name=$txt$Grupo Riquelme$txt$), $txt$EMCESA (gaseosas Niko, De la Costa; ex Arci Cola)$txt$, $txt$Bebidas$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Riquelme$txt$), $txt$CCA – Cervecera Asunción (Munich, Victoria, Polar)$txt$, $txt$Bebidas$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Riquelme$txt$), $txt$Cadena Real (supermercados)$txt$, $txt$Retail$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Riquelme$txt$), $txt$Cereales SA / Fideos Federal (molinos harineros)$txt$, $txt$Alimentos$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Riquelme$txt$), $txt$Campos Morombí (agro, ganadería y reserva natural privada)$txt$, $txt$Agro$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Riquelme$txt$), $txt$Indel SA / Monarca (inversiones recientes)$txt$, $txt$Industria$txt$, null, 6),

((select id from market_groups where name=$txt$Grupo Pettengill$txt$), $txt$Frigorífico Guaraní (+ línea de snacks Taco Villa)$txt$, $txt$Agroindustria$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Pettengill$txt$), $txt$Ocho A SA (constructora)$txt$, $txt$Construcción$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Pettengill$txt$), $txt$Constructora Paraná$txt$, $txt$Construcción$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Pettengill$txt$), $txt$Dysa Healthcare (insumos médicos)$txt$, $txt$Salud$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Pettengill$txt$), $txt$Consorcio Corredor Vial Bioceánico$txt$, $txt$Construcción$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Pettengill$txt$), $txt$Consorcio Rutas del Este (Ruta 2 y 7)$txt$, $txt$Construcción$txt$, null, 6),

((select id from market_groups where name=$txt$Grupo Ortega$txt$), $txt$Barcos & Rodados (en transición a Shell, JV con Raízen)$txt$, $txt$Combustibles$txt$, null, 1),

((select id from market_groups where name=$txt$Grupo Martín Martín$txt$), $txt$Fuelpar (combustibles y lubricantes)$txt$, $txt$Combustibles$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Martín Martín$txt$), $txt$Districom (logística de distribución)$txt$, $txt$Logística$txt$, null, 2),

((select id from market_groups where name=$txt$Grupo Luminotecnia$txt$), $txt$Luminotecnia (cadena retail, 20 locales)$txt$, $txt$Retail$txt$, 'topofmind', 1),
((select id from market_groups where name=$txt$Grupo Luminotecnia$txt$), $txt$División Corporativa (proyectos industriales y de obra)$txt$, $txt$Construcción$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Luminotecnia$txt$), $txt$Fabrimet (fabricación de artefactos de iluminación y muebles metálicos)$txt$, $txt$Industria$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Luminotecnia$txt$), $txt$Distribución de materiales eléctricos (mayorista para comercios del rubro)$txt$, $txt$Construcción$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Luminotecnia$txt$), $txt$Climatización y herramientas (línea VCP)$txt$, $txt$Construcción$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Luminotecnia$txt$), $txt$Tecnología, redes y cableado estructurado (línea VCP)$txt$, $txt$Industria$txt$, null, 6),
((select id from market_groups where name=$txt$Grupo Luminotecnia$txt$), $txt$Instalaciones electromecánicas llave en mano$txt$, $txt$Construcción$txt$, null, 7),

((select id from market_groups where name=$txt$Grupo Alkan (Hoeckle)$txt$), $txt$Monte Alegre SA (importación, almacenamiento y logística de combustibles)$txt$, $txt$Combustibles$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Alkan (Hoeckle)$txt$), $txt$Imperial SA / Petromax (distribución, ~110 estaciones de servicio)$txt$, $txt$Combustibles$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Alkan (Hoeckle)$txt$), $txt$Petroquim SA (operación de estaciones propias)$txt$, $txt$Combustibles$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Alkan (Hoeckle)$txt$), $txt$Terminal Occidental S.A. (TOSA) — zona franca de servicios en Villa Hayes (US$22M)$txt$, $txt$Logística$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Alkan (Hoeckle)$txt$), $txt$TOSA — plan maestro urbano Chaco'i (proyectos Barrio Norte y La Isla del Chaco desde 2013; 1.400 ha, potencial de inversión de US$4.000M: parque industrial de 222 lotes, zona residencial de 1.000 lotes con capacidad para 2.300 viviendas, torre de 19 pisos, hotelería, comercio y área ecoturística)$txt$, $txt$Inmobiliario$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Alkan (Hoeckle)$txt$), $txt$AZPA — Azucarera Paraguaya S.A. (110+ años, líder mundial en exportación de azúcar orgánica, ~100.000 ton/año de capacidad)$txt$, $txt$Agroindustria$txt$, null, 6),
((select id from market_groups where name=$txt$Grupo Alkan (Hoeckle)$txt$), $txt$Envapar — Envases Paraguayos S.A. (40+ años, envases plásticos rígidos y flexibles, exporta a Brasil, Argentina, Uruguay, Bolivia, Chile y Perú)$txt$, $txt$Industria$txt$, null, 7),
((select id from market_groups where name=$txt$Grupo Alkan (Hoeckle)$txt$), $txt$Navesur (transporte fluvial de carga, flota de remolcadores y barcazas)$txt$, $txt$Logística$txt$, null, 8),
((select id from market_groups where name=$txt$Grupo Alkan (Hoeckle)$txt$), $txt$Monteverde (campos agrícolas)$txt$, $txt$Agro$txt$, null, 9),

((select id from market_groups where name=$txt$Grupo Toyotoshi$txt$), $txt$Toyotoshi SA (representante de Toyota, Hino Motors, próx. Lexus)$txt$, $txt$Automotor$txt$, 'gptw', 1),
((select id from market_groups where name=$txt$Grupo Toyotoshi$txt$), $txt$AutoMarket SA (camiones Hino y Toyota Material Handling — montacargas)$txt$, $txt$Automotor$txt$, 'gptw', 2),
((select id from market_groups where name=$txt$Grupo Toyotoshi$txt$), $txt$Distrimotor SA$txt$, $txt$Automotor$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Toyotoshi$txt$), $txt$Estancia Keiko SA (agro/ganadería)$txt$, $txt$Agro$txt$, null, 4),
((select id from market_groups where name=$txt$Grupo Toyotoshi$txt$), $txt$Transmar SA$txt$, $txt$Logística$txt$, null, 5),
((select id from market_groups where name=$txt$Grupo Toyotoshi$txt$), $txt$Transporte Fluvial Paraguayo SACI$txt$, $txt$Logística$txt$, null, 6),
((select id from market_groups where name=$txt$Grupo Toyotoshi$txt$), $txt$TG Cuir International$txt$, $txt$Industria$txt$, null, 7),

((select id from market_groups where name=$txt$Distribuidora Gloria$txt$), $txt$Distribución Philip Morris International (tabaco)$txt$, $txt$Tabaco$txt$, null, 1),
((select id from market_groups where name=$txt$Distribuidora Gloria$txt$), $txt$Distribución Kraft Foods / Mondelez$txt$, $txt$Chocolates, golosinas y snacks$txt$, null, 2),
((select id from market_groups where name=$txt$Distribuidora Gloria$txt$), $txt$Distribución Miller Brewing Co. (cerveza)$txt$, $txt$Bebidas$txt$, null, 3),
((select id from market_groups where name=$txt$Distribuidora Gloria$txt$), $txt$Distribución Viñedos Peñaflor (vinos)$txt$, $txt$Bebidas alcohólicas importadas$txt$, null, 4),
((select id from market_groups where name=$txt$Distribuidora Gloria$txt$), $txt$Distribución Jugos del Valle$txt$, $txt$Bebidas$txt$, null, 5),
((select id from market_groups where name=$txt$Distribuidora Gloria$txt$), $txt$Distribución Pilas Red Power$txt$, $txt$Industria$txt$, null, 6),

((select id from market_groups where name=$txt$Grupo Gorostiaga$txt$), $txt$Gorostiaga Automóviles (Changan, Nissan, Isuzu, Hyundai, Mitsubishi, Scania usados)$txt$, $txt$Automotor$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Gorostiaga$txt$), $txt$Gorostiaga Inmobiliaria$txt$, $txt$Inmobiliario$txt$, null, 2),

((select id from market_groups where name=$txt$Grupo Cogorno$txt$), $txt$Shopping China (retail de importados — 3 sucursales en zona de frontera + filiales en Bolivia y Uruguay)$txt$, $txt$Retail$txt$, null, 1),
((select id from market_groups where name=$txt$Grupo Cogorno$txt$), $txt$Fortis Mayorista (cash & carry, 6-7 locales, Top of Mind del rubro 2 años consecutivos)$txt$, $txt$Retail$txt$, null, 2),
((select id from market_groups where name=$txt$Grupo Cogorno$txt$), $txt$Interfisa Banco SAECA (control accionario mayoritario desde 2020, vía Maestral S.A. y Mercadis S.A.)$txt$, $txt$Financiero$txt$, null, 3),
((select id from market_groups where name=$txt$Grupo Cogorno$txt$), $txt$Río Seguros S.A. (adquirida por Interfisa en 2025, ex-subsidiaria de Banco Río)$txt$, $txt$Seguros$txt$, null, 4);

-- =========================================================================
-- market_independent_sections (24 secciones)
-- =========================================================================
insert into market_independent_sections (rubro, sort_order) values
($txt$Banca$txt$, 1),
($txt$Financieras$txt$, 2),
($txt$Casas de crédito / crédito de consumo$txt$, 3),
($txt$Casas de cambio$txt$, 4),
($txt$Cooperativas de ahorro y crédito$txt$, 5),
($txt$Seguros$txt$, 6),
($txt$Retail / supermercados$txt$, 7),
($txt$Consumo masivo — alimentos envasados y golosinas$txt$, 8),
($txt$Consumo masivo — motos, bicicletas y equipamiento$txt$, 9),
($txt$Electrodomésticos y tecnología (retail a crédito)$txt$, 10),
($txt$Logística fluvial / hidrovía$txt$, 11),
($txt$Consumo masivo — cuidado personal y del hogar$txt$, 12),
($txt$Automotor (concesionarios adicionales)$txt$, 13),
($txt$Combustibles — emblemas adicionales$txt$, 14),
($txt$Construcción — grandes contratistas$txt$, 15),
($txt$Agroindustria — insumos, acopio y trading de granos$txt$, 16),
($txt$Bebidas / consumo masivo$txt$, 17),
($txt$Industria / agroindustria$txt$, 18),
($txt$Retail — cadenas de farmacias$txt$, 19),
($txt$Inmobiliario — desarrolladoras (top y media)$txt$, 20),
($txt$Inmobiliario — loteadoras (venta de terrenos en cuotas)$txt$, 21),
($txt$Salud — medicina prepaga independiente$txt$, 22),
($txt$Farmacéutica — laboratorios e insumos médicos$txt$, 23),
($txt$Telecomunicaciones / logística$txt$, 24);

-- =========================================================================
-- market_independent_items (120 empresas independientes)
-- =========================================================================
insert into market_independent_items (section_id, nombre, rubro, nota, badge, sort_order) values
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Banco Itaú Paraguay$txt$, null, $txt$Mayor banco por ingresos del país (~US$155M/año) — Forbes Paraguay.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Banco Continental$txt$, null, $txt$Uno de los bancos líderes por activos.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Banco GNB Paraguay$txt$, null, $txt$44% de sus acciones pertenece al Grupo Vierci — no es 100% independiente.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Banco Sudameris$txt$, null, $txt$Filial de banca internacional.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Banco Regional$txt$, null, $txt$Fuerte presencia en agronegocio.$txt$, null, 5),
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Banco Familiar$txt$, null, $txt$Foco históricamente en consumo y microfinanzas.$txt$, null, 6),
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Banco BBVA Paraguay$txt$, null, $txt$Filial española.$txt$, 'gptw', 7),
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Visión Banco$txt$, null, $txt$Foco en microfinanzas y bancarización.$txt$, null, 8),
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Banco Nacional de Fomento (BNF)$txt$, null, $txt$Banco público, principal financiador estatal de proyectos productivos.$txt$, null, 9),
((select id from market_independent_sections where rubro=$txt$Banca$txt$), $txt$Banco Río$txt$, null, $txt$Banco de capital nacional, orientado a agro y comercio.$txt$, null, 10),

((select id from market_independent_sections where rubro=$txt$Financieras$txt$), $txt$Financiera FIC$txt$, null, $txt$Financiera de consumo, una de las más antiguas del mercado.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Financieras$txt$), $txt$Financiera Solar$txt$, null, $txt$Consumo y microcréditos.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Financieras$txt$), $txt$Financiera Paraguayo Japonesa (Fiado)$txt$, null, $txt$Foco en pymes.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Financieras$txt$), $txt$Financiera Ueno$txt$, null, $txt$Consumo masivo, fuerte presencia digital.$txt$, null, 4),

((select id from market_independent_sections where rubro=$txt$Casas de crédito / crédito de consumo$txt$), $txt$Tarjetas de crédito (Visión Banco, Cabal, Panal, Credicard)$txt$, null, $txt$Ecosistema de tarjetas y crédito de consumo, muy activo en retail.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Casas de crédito / crédito de consumo$txt$), $txt$Casas de empeño y créditos rápidos (varias marcas regionales)$txt$, null, $txt$Segmento informal/semi-formal de alta rotación de personal en cobranzas y ventas.$txt$, null, 2),

((select id from market_independent_sections where rubro=$txt$Casas de cambio$txt$), $txt$Casa de Cambios Chaco$txt$, null, $txt$Una de las redes de cambio más grandes del país.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Casas de cambio$txt$), $txt$Cambios Alberdi$txt$, null, $txt$Fuerte presencia fronteriza (Ciudad del Este).$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Casas de cambio$txt$), $txt$La Paraguaya S.A. de Cambios$txt$, null, $txt$Red nacional de sucursales de cambio.$txt$, null, 3),

((select id from market_independent_sections where rubro=$txt$Cooperativas de ahorro y crédito$txt$), $txt$Cooperativa Universitaria$txt$, null, $txt$Una de las cooperativas más grandes del país por activos.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Cooperativas de ahorro y crédito$txt$), $txt$Cooperativa Medalla Milagrosa$txt$, null, $txt$Gran base de socios en Asunción y Gran Asunción.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Cooperativas de ahorro y crédito$txt$), $txt$Cooperativa Ñemby$txt$, null, $txt$Fuerte presencia en el sur de Asunción.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Cooperativas de ahorro y crédito$txt$), $txt$Cooperativa Chortitzer$txt$, null, $txt$Base en colonias menonitas del Chaco, fuerte en agro.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Cooperativas de ahorro y crédito$txt$), $txt$Coomecipar$txt$, null, $txt$Cooperativa multiactiva de alcance nacional.$txt$, null, 5),
((select id from market_independent_sections where rubro=$txt$Cooperativas de ahorro y crédito$txt$), $txt$Cooperativa San Cristóbal$txt$, null, $txt$Multiactiva, ahorro y crédito, servicios y producción.$txt$, null, 6),
((select id from market_independent_sections where rubro=$txt$Cooperativas de ahorro y crédito$txt$), $txt$Cooperativa de las Fuerzas Armadas de la Nación$txt$, null, $txt$Base de socios ligada a las FF.AA.$txt$, null, 7),

((select id from market_independent_sections where rubro=$txt$Seguros$txt$), $txt$Mapfre Paraguay$txt$, null, $txt$Líder en primas directas del mercado: US$72,5 millones en el ejercicio 2024/2025 (13,1% de participación).$txt$, 'gptw', 1),
((select id from market_independent_sections where rubro=$txt$Seguros$txt$), $txt$Patria S.A. de Seguros y Reaseguros$txt$, null, $txt$Mayor patrimonio neto del sector: US$74,1 millones; segundo lugar en utilidades del ejercicio 2025/2026 con 17,19% de participación de mercado.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Seguros$txt$), $txt$Itaú Seguros Paraguay$txt$, null, $txt$Líder en utilidades del ejercicio 2025/2026: US$8,8 millones (28,17% de participación de mercado). Brazo asegurador del banco Itaú.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Seguros$txt$), $txt$Sudameris Seguros$txt$, null, $txt$Brazo asegurador del Grupo Sudameris, lanzado en febrero de 2024 con el objetivo declarado de ubicarse entre los tres primeros del ranking en los próximos años.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Seguros$txt$), $txt$Ueno Seguros$txt$, null, $txt$Aseguradora del banco digital Ueno, habilitada en seguros generales y de vida. Certificada Great Place to Work (diciembre 2025, 83% de favorabilidad, 31 colaboradores).$txt$, 'gptw', 5),

((select id from market_independent_sections where rubro=$txt$Retail / supermercados$txt$), $txt$Casa Rica + Areté (Comercializadora de Alimentos Frescos SA)$txt$, null, $txt$Mismo grupo comercial; posicionamiento premium.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Retail / supermercados$txt$), $txt$Salemma$txt$, null, $txt$Cadena de supermercados de alcance nacional — Elzear Salemma, su propietario, es expresidente de la Cámara Paraguaya de Supermercados (Capasu).$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Retail / supermercados$txt$), $txt$Los Jardines / Gran Vía / Pueblo / LT$txt$, null, $txt$Cadenas locales con fuerte presencia barrial.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Retail / supermercados$txt$), $txt$Metro / City Market / Archi / Oviedo (Sarambi-Machetazo)$txt$, null, $txt$Cadenas regionales, varias del interior del país.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Retail / supermercados$txt$), $txt$Villamorra Shopping$txt$, null, $txt$Centro comercial referente en Asunción.$txt$, 'gptw', 5),

((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$Nestlé Paraguay — Café e infusiones (Nescafé, Dolce Gusto)$txt$, $txt$Café e infusiones$txt$, $txt$Operación directa desde 1998 (antes vía distribuidor Imexpaco desde 1964).$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$Nestlé Paraguay — Lácteos y alimentos (Nido, Moca, Nestum)$txt$, $txt$Alimentos y condimentos$txt$, $txt$Parte del portafolio local de Nestlé desde 1998.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$Nestlé Paraguay — Helados$txt$, $txt$Helados$txt$, $txt$Línea de helados de Nestlé en Paraguay.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$Nestlé Paraguay — Alimento para mascotas$txt$, $txt$Alimento para mascotas$txt$, $txt$Línea de pet food de Nestlé en Paraguay.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$Nestlé Business Services Latam (NBS, Asunción)$txt$, $txt$Servicios corporativos$txt$, $txt$Hub de servicios compartidos de Nestlé para 21 países, 1.000+ colaboradores, inversión acumulada +US$8M — no es una línea de consumo, es un centro de servicios regional.$txt$, null, 5),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$Arcor Paraguay$txt$, $txt$Chocolates, golosinas y snacks$txt$, $txt$Multinacional argentina de golosinas, galletas, chocolates y helados — oficina propia en Asunción (Torres del Paseo). Compite con DDA (Milka/Toblerone) y Distribuidora Gloria (Kraft/Mondelez) en golosinas y chocolates.$txt$, null, 6),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$DDA — Distribuidora Dirigida S.A.$txt$, $txt$Chocolates, golosinas y snacks$txt$, $txt$25 años de trayectoria en importación y distribución de alimentos — importa entre otras las marcas Milka y Toblerone. Compite con Arcor y Distribuidora Gloria (Kraft/Mondelez) en chocolates.$txt$, null, 7),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$MG Importadora Exportadora SRL$txt$, $txt$Alimentos y condimentos$txt$, $txt$29 años de trayectoria, centro logístico de 10.000m² en Fernando de la Mora. Representa las marcas Si Diet, De la Huerta y Gota Limpa (esta última también compite en limpieza del hogar), con fuerza de ventas propia en canal tradicional y moderno.$txt$, null, 8),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$Danone Paraguay (vía Trovato CISA)$txt$, $txt$Lácteos y postres$txt$, $txt$Trovato CISA, empresa paraguaya con 55+ años de trayectoria en fabricación, importación y distribución, es la distribuidora local de Danone/La Serenísima (Activia, Actimel, Ser, Danonino, Serenito, Villavicencio, Villa del Sur).$txt$, null, 9),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — alimentos envasados y golosinas$txt$), $txt$Cervepar (Grupo Vierci)$txt$, null, $txt$Ya mapeada dentro de Grupo Vierci — se referencia acá para el contexto de la categoría.$txt$, null, 10),

((select id from market_independent_sections where rubro=$txt$Consumo masivo — motos, bicicletas y equipamiento$txt$), $txt$Grupo Chacomer$txt$, null, $txt$Uno de los conglomerados más importantes del país en motos y bicicletas, +100 marcas en portafolio. Planta industrial propia de 45.000 m² (motos, bicicletas, gimnasio). Ganancias 2021: G.140.758M (~US$20M), +177% vs. año anterior. 68 locales propios + 4.000 distribuidores.$txt$, null, 1),

((select id from market_independent_sections where rubro=$txt$Electrodomésticos y tecnología (retail a crédito)$txt$), $txt$Unicomer / Electro Fácil$txt$, null, $txt$Multinacional salvadoreña (21+ países), dueña de Gollo, La Curacao, RadioShack. En Paraguay opera como Electro Fácil desde 2015, aliada con Grupo A.M. Reguera (representante de Electrolux, Frigidaire, White-Westinghouse) desde 2023. Modelo de negocio basado en crédito propio — compite directo con Luminotecnia en climatización/tecnología.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Electrodomésticos y tecnología (retail a crédito)$txt$), $txt$Grupo Luminotecnia$txt$, null, $txt$Ya mapeado como grupo familiar — referencia cruzada: líder de Top of Mind en electricidad, compite con Electro Fácil/Unicomer en tecnología y climatización.$txt$, null, 2),

((select id from market_independent_sections where rubro=$txt$Logística fluvial / hidrovía$txt$), $txt$Grupo Dos Santos$txt$, null, $txt$Uno de los operadores más tradicionales de la hidrovía Paraguay-Paraná. Compró en 2025 el armador fluvial Río Sur (ex Chacomer) — 1 remolcador + 12 barcazas, 33.300 ton de capacidad. Compite con Cargo Line (Grupo Zapag).$txt$, null, 1),

((select id from market_independent_sections where rubro=$txt$Consumo masivo — cuidado personal y del hogar$txt$), $txt$Unilever Paraguay — Cuidado personal (Rexona, Dove, Sedal, Lux)$txt$, $txt$Cuidado personal e higiene$txt$, $txt$Presente desde 1996 (compró marcas/red de distribución de CAPSA). ~150 empleados directos + ~1.000 indirectos. Compite con Kimberly-Clark en cuidado personal.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — cuidado personal y del hogar$txt$), $txt$Unilever Paraguay — Limpieza del hogar (OMO, Brillante)$txt$, $txt$Limpieza del hogar$txt$, $txt$Línea de detergentes y limpieza de Unilever en Paraguay.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — cuidado personal y del hogar$txt$), $txt$Unilever Paraguay — Alimentos y condimentos (Hellmann's, Knorr, Maizena, Sabora, Kuñatai)$txt$, $txt$Alimentos y condimentos$txt$, $txt$Nuevo centro de distribución en Villeta (17.500m², US$16,5M, certificación LEED plata) sirve a las tres líneas de Unilever.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — cuidado personal y del hogar$txt$), $txt$Kimberly-Clark Paraguay$txt$, $txt$Cuidado personal e higiene$txt$, $txt$Presente desde 1997 (inicialmente vía Unilever como socio comercial). Desde 2021 pasó a un modelo de comercialización directa sin intermediarios y duplicó su dotación de colaboradores. Marcas: Huggies, Kotex, Scott, Kleenex, Poise, Plenitud y línea profesional. Compite con Unilever en cuidado personal.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — cuidado personal y del hogar$txt$), $txt$Brumado S.A.$txt$, $txt$Bebidas alcohólicas importadas$txt$, $txt$34 años de trayectoria como importador y distribuidor — cervezas, vinos, whiskys y vodkas, con depósito en el Parque Mercosur (Ciudad del Este). Compite con Vascol y con la línea de espirituosas de Grupo Vierci.$txt$, null, 5),
((select id from market_independent_sections where rubro=$txt$Consumo masivo — cuidado personal y del hogar$txt$), $txt$Vascol S.A.C.I.$txt$, $txt$Bebidas alcohólicas importadas$txt$, $txt$Importador y distribuidor con sede en Luque — representante de bodegas argentinas como Norton (Mendoza). Compite con Brumado y con la línea de espirituosas de Grupo Vierci.$txt$, null, 6),

((select id from market_independent_sections where rubro=$txt$Automotor (concesionarios adicionales)$txt$), $txt$Perfecta Automotores$txt$, $txt$Automotor$txt$, $txt$Concesionario de BMW en Paraguay — compite con Bogarín (Maserati), Toyotoshi (Toyota/Lexus) y Gorostiaga en el segmento premium/generalista.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Automotor (concesionarios adicionales)$txt$), $txt$Diesa S.A.$txt$, $txt$Automotor$txt$, $txt$Representante en Paraguay de Volkswagen, Audi, Porsche, Honda y Scania — 60 años de operación. Compite con Garden (KIA/Chevrolet/Mazda/Nissan/grupo Chrysler) y Toyotoshi en el segmento multimarca.$txt$, null, 2),

((select id from market_independent_sections where rubro=$txt$Combustibles — emblemas adicionales$txt$), $txt$Puma Energy$txt$, $txt$Combustibles$txt$, $txt$Multinacional (control de Trafigura desde 1997, marca creada en Argentina en 1929) — cerca de 160 estaciones en Paraguay, entre los 5 primeros emblemas del mercado. Terminales propias en San Antonio, Encarnación y Alto Paraná. Compite con Copetrol (Zapag), Shell (Ortega/Raízen), Petromax (Alkan) y Fuelpar (Martín Martín).$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Combustibles — emblemas adicionales$txt$), $txt$Petropar (Petróleos Paraguayos)$txt$, $txt$Combustibles$txt$, $txt$Petrolera estatal — importa y comercializa combustibles y biocombustibles, y funciona como referencia de precios estables para todo el mercado. Designada en 2014 para representar al Estado en exploración y explotación de hidrocarburos.$txt$, null, 2),

((select id from market_independent_sections where rubro=$txt$Construcción — grandes contratistas$txt$), $txt$Tecnoedil S.A. Constructora$txt$, $txt$Construcción$txt$, $txt$Constructora paraguaya desde 1978, especialista en obras viales, civiles y portuarias. Matriz de empresas de asfalto, concreto, pretensados y arriendo de maquinaria. Expansión regional: Uruguay, Perú, Brasil, EE.UU. Compite con Ocho A (Pettengill) y Concret Mix (Bogarín) en licitaciones estatales. En 2026 integra el consorcio Rutas del Mercosur (con ALYA, SEMISA y Construpar) adjudicado para la Ruta PY01.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Construcción — grandes contratistas$txt$), $txt$Tocsa S.A.$txt$, $txt$Construcción$txt$, $txt$Mayor monto adjudicado en contratos de obra pública entre 2018 y 2020 según ranking de Última Hora sobre las 20 principales contratistas del Estado: US$247 millones.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Construcción — grandes contratistas$txt$), $txt$Constructora Heisecke S.A.$txt$, $txt$Construcción$txt$, $txt$Entre los mayores contratistas de obra pública del país en el período 2018-2020, con US$158 millones adjudicados (Última Hora).$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Construcción — grandes contratistas$txt$), $txt$Construpar S.A.$txt$, $txt$Construcción$txt$, $txt$Entre las 20 principales contratistas del Estado en el período 2018-2020 (Última Hora). En 2026 integra junto a Tecnoedil el consorcio Rutas del Mercosur adjudicado para la Ruta PY01.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Construcción — grandes contratistas$txt$), $txt$Benito Roggio e Hijos S.A.$txt$, $txt$Construcción$txt$, $txt$Constructora argentina con operación en Paraguay — ejecutó el Corredor Vial Botánico, entre otras obras viales adjudicadas por el Estado.$txt$, null, 5),
((select id from market_independent_sections where rubro=$txt$Construcción — grandes contratistas$txt$), $txt$Constructora Feldmann S.A.$txt$, $txt$Construcción$txt$, $txt$Adjudicada en 2026 para la pavimentación de 25,77 km del Plan Central 3 – Lote 2 (Itauguá), con una inversión de G. 38.474.983.828.$txt$, null, 6),

((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$Agrofértil S.A. (Grupo Sarabia)$txt$, null, $txt$Mayor proveedor de insumos agrícolas del país desde 1993 — fertilizantes, semillas, agroquímicos, asistencia técnica. Red de silos con 780.000 tn de capacidad total en Paraguay.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$Agrotec S.A.$txt$, null, $txt$Proveedor de insumos y tecnología agrícola.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$Agro Química del Paraguay$txt$, null, $txt$Agroquímicos y productos biológicos para tratamiento de semillas.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$Cargill Paraguay$txt$, null, $txt$Multinacional estadounidense — originación, acopio, procesamiento y exportación de granos y oleaginosas. Uno de los mayores exportadores de soja del país.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$ADM Paraguay$txt$, null, $txt$Opera en el país desde 1997. ~1.000 empleados, procesa ~30% de la producción nacional de granos y oleaginosas. Planta de fertilizantes + crushing de soja en Villeta, 32 elevadores, 14 remolcadores, 200 barcazas propias, puerto propio. Subsidiaria naviera: Naviera Chaco.$txt$, null, 5),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$Bunge Paraguay$txt$, null, $txt$Multinacional de trading agrícola — planta de molienda en Villeta (con LDC), ~1,3M ton/año de capacidad.$txt$, null, 6),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$Louis Dreyfus Company (LDC) Paraguay$txt$, null, $txt$Trading agrícola global — aliada con Bunge en molienda en Villeta.$txt$, null, 7),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$AGD / Copagra (Consorcio CAIASA)$txt$, null, $txt$Consorcio argentino-paraguayo de procesamiento de oleaginosas en Villeta.$txt$, null, 8),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$COFCO International Services Paraguay$txt$, null, $txt$Trading agrícola de capital chino, presencia consolidada en el país.$txt$, null, 9),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$Noble Group Paraguay$txt$, null, $txt$Trading agrícola — terreno propio de 60 hectáreas para puerto en Villeta.$txt$, null, 10),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$CHS / Nidera Paraguay$txt$, null, $txt$Oficinas instaladas en el país tras el boom de la industria aceitera.$txt$, null, 11),
((select id from market_independent_sections where rubro=$txt$Agroindustria — insumos, acopio y trading de granos$txt$), $txt$Bayer / Monsanto Paraguay$txt$, null, $txt$Ya referenciada en Industria — multinacional agro-biotecnológica, semillas y agroquímicos.$txt$, 'gptw', 12),

((select id from market_independent_sections where rubro=$txt$Bebidas / consumo masivo$txt$), $txt$Paresa Paraguay (Coca-Cola)$txt$, null, $txt$Embotellador de Coca-Cola — compite directo con BDP (Vierci/CCU) y CCA (Riquelme). +40 productos, 65.000 clientes directos, top 4 aportante al fisco.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Bebidas / consumo masivo$txt$), $txt$British American Tobacco Paraguay$txt$, null, $txt$Tabacalera multinacional, compite con Tabesa (ex-Cartes).$txt$, 'gptw', 2),

((select id from market_independent_sections where rubro=$txt$Industria / agroindustria$txt$), $txt$Inpasa Paraguay$txt$, null, $txt$Una de las mayores plantas de etanol de maíz de Sudamérica.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Industria / agroindustria$txt$), $txt$Beef Paraguay$txt$, null, $txt$Frigorífico exportador, entre los mayores aportantes al fisco del sector.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Industria / agroindustria$txt$), $txt$Monsanto / Bayer Paraguay$txt$, null, $txt$Multinacional agro-biotecnológica.$txt$, 'gptw', 3),

((select id from market_independent_sections where rubro=$txt$Retail — cadenas de farmacias$txt$), $txt$Punto Farma$txt$, $txt$Retail$txt$, $txt$Mayor cadena de farmacias del país por cantidad de locales: 700+ sucursales en todos los departamentos. Fundada en 2001 por Víctor Muñoz Sosa. Compite directo con FarmaOliva (Grupo Harrison) y Farmacenter (Grupo Cartes Montaña).$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Retail — cadenas de farmacias$txt$), $txt$Farmacias Catedral$txt$, $txt$Retail$txt$, $txt$Una de las principales cadenas de farmacias del país, con 161 sucursales.$txt$, null, 2),

((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$ZUBA$txt$, $txt$Inmobiliario$txt$, $txt$Fundada en 2017 por Alejandro Zuccolillo Quevedo (sobrino de Aldo Zuccolillo, fundador de Grupo Azeta — empresa independiente, no forma parte de la estructura corporativa de Azeta) y Valentina Basaglia. Primera desarrolladora paraguaya en obtener grado de inversión de Fitch Ratings (A-py, nov. 2024). 22+ proyectos en desarrollo, 700+ departamentos entregados en 7 años, ritmo de 300-400 entregas anuales.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$Altius Group$txt$, $txt$Inmobiliario$txt$, $txt$Desarrolladora uruguaya en expansión a Paraguay, Panamá y México. Proyectos More del Sol (torre de 27 pisos, US$18M) y More Mariscal (dos torres de uso mixto, US$50M).$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$GONU$txt$, $txt$Inmobiliario$txt$, $txt$Opera desde 1999 — líder en viviendas unifamiliares de lujo y barrios cerrados en Asunción y Gran Asunción, 426.000+ m² construidos, 7 countries entregados.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$Petra Urbana$txt$, $txt$Inmobiliario$txt$, $txt$Fundada en 2016, foco en renovación urbana vertical — desarrolla Petra Tower, el edificio más alto de Asunción. 11 proyectos completados y 9 en ejecución.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$EYDISA$txt$, $txt$Inmobiliario$txt$, $txt$Desarrolladora de origen argentino (2007), presente en Paraguay desde 2013. Proyectos Park Plaza, series SkyPark, Bali y Marena.$txt$, null, 5),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$AZ Inversiones (Grupo Sindec)$txt$, $txt$Inmobiliario$txt$, $txt$Parte de Grupo Sindec, conglomerado familiar de 9 empresas (AZ Inversiones, Ganadera Campo Verde, Urbania, REMAX Urbana, Nodal, Inversoy, Panamerica, entre otras) liderado por Simón Jara. AZ Inversiones: 448 unidades entregadas y 1.018 en desarrollo (proyectos Zenith, España Las Mercedes).$txt$, null, 6),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$Raíces Real Estate$txt$, $txt$Inmobiliario$txt$, $txt$Fundada en 2004 por Jorge Figueredo Fleitas, equipo de 300 personas. Proyectos Aquadelta, Aquabrava y Aquaterra.$txt$, null, 7),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$Urban Domus$txt$, $txt$Inmobiliario$txt$, $txt$Capital chileno, en el mercado paraguayo desde 2014. 7+ proyectos residenciales (1488 Colman, Urban Molas, Lomas 1820, Izara Barrio Privado).$txt$, null, 8),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$Fortaleza Inmuebles$txt$, $txt$Inmobiliario$txt$, $txt$La más antigua identificada en este relevamiento: opera desde 1922. Proyectos Fortaleza Carmelitas, Fortaleza Molas López y Fortaleza Boggiani.$txt$, null, 9),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$Consorcio JGL Casatua$txt$, $txt$Inmobiliario$txt$, $txt$Une a Casatua (30+ años) con Jiménez Gaona y Lima — esta última ya mapeada como constructora de Grupo Cartes/Cartes Montaña. Proyectos Casa M, Met Las Lomas y Met Molas López.$txt$, null, 10),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — desarrolladoras (top y media)$txt$), $txt$Codesarrollos$txt$, $txt$Inmobiliario$txt$, $txt$Fundada en 2018 en Asunción — línea de proyectos "Belive" (Belive Molas II, Belive Garay, Belive Sajonia, Belive Sicilia).$txt$, null, 11),

((select id from market_independent_sections where rubro=$txt$Inmobiliario — loteadoras (venta de terrenos en cuotas)$txt$), $txt$La Loteadora Inmobiliaria S.A.$txt$, $txt$Loteadoras$txt$, $txt$64 años en el mercado, 313 loteamientos activos en todo el país y más de 40.000 títulos entregados. Miembro fundador de CAPELI (Cámara Paraguaya de Empresas Loteadoras e Inmobiliarias, fundada en 1983, 46 empresas asociadas).$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — loteadoras (venta de terrenos en cuotas)$txt$), $txt$Rodán Inmobiliaria$txt$, $txt$Loteadoras$txt$, $txt$Venta de lotes en todo el país, en cuotas sin reajuste y hasta 130 meses de plazo.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — loteadoras (venta de terrenos en cuotas)$txt$), $txt$La Paraguaya Inmobiliaria S.A. (LPI)$txt$, $txt$Loteadoras$txt$, $txt$Loteamientos en las principales ciudades del país.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — loteadoras (venta de terrenos en cuotas)$txt$), $txt$Loterra$txt$, $txt$Loteadoras$txt$, $txt$Loteadora inmobiliaria con operación nacional.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Inmobiliario — loteadoras (venta de terrenos en cuotas)$txt$), $txt$Urba (Desarrolladora Urbana S.A.)$txt$, $txt$Loteadoras$txt$, $txt$Loteamientos en la zona de Chaco'i — compite directamente con el plan maestro urbano de TOSA (Grupo Alkan) en la misma zona.$txt$, null, 5),

((select id from market_independent_sections where rubro=$txt$Salud — medicina prepaga independiente$txt$), $txt$Grupo Epem$txt$, $txt$Salud$txt$, $txt$Primera empresa de emergencias médicas móviles del país, fundada en 1991 en Fernando de la Mora. Combina medicina prepaga, emergencias 24/7, odontología, medicina laboral y estética con cobertura nacional.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Salud — medicina prepaga independiente$txt$), $txt$Promed (Protección Médica S.A.)$txt$, $txt$Salud$txt$, $txt$⚠️ Medicina prepaga fundada en 1980 por el Dr. José Luis Daglio Tanco (Grupo Daglio), quien la operó junto al Sanatorio AMSA por 50 años. En febrero de 2024 el fundador se retiró y vendió el paquete mayoritario a un grupo empresarial que no reveló su identidad públicamente — verificar composición societaria actual antes de cualquier proceso.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Salud — medicina prepaga independiente$txt$), $txt$Salud Protegida$txt$, $txt$Salud$txt$, $txt$Empresa de medicina prepaga registrada ante la Superintendencia de Salud.$txt$, null, 3),

((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Laboratorios LASCA$txt$, null, $txt$Industria farmacéutica líder de capital 100% paraguayo — el mayor laboratorio nacional.$txt$, null, 1),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Laboratorios Bagó del Paraguay$txt$, null, $txt$Filial de la multinacional argentina Bagó (11 plantas en el mundo, presencia en 20 países).$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Sanofi Aventis Paraguay$txt$, null, $txt$Filial de la multinacional farmacéutica francesa.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Gador Paraguay$txt$, null, $txt$Filial de laboratorio argentino.$txt$, null, 4),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$MegaLabs Paraguay$txt$, null, $txt$Multinacional uruguaya, uno de los mayores laboratorios de la región.$txt$, null, 5),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Laboratorios Siegfried$txt$, null, $txt$Laboratorio de capital nacional.$txt$, null, 6),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Farmacéutica Paraguaya S.A.$txt$, null, $txt$Laboratorio de capital nacional, larga trayectoria.$txt$, null, 7),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Comfar S.A.E.C.A.$txt$, null, $txt$Laboratorio nacional.$txt$, null, 8),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Laboratorios Galeno$txt$, null, $txt$Laboratorio nacional.$txt$, null, 9),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Indufar C.I.S.A.$txt$, null, $txt$Laboratorio nacional.$txt$, null, 10),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$B. Braun Medical Paraguay$txt$, null, $txt$Multinacional alemana de insumos y equipamiento médico-hospitalario.$txt$, null, 11),
((select id from market_independent_sections where rubro=$txt$Farmacéutica — laboratorios e insumos médicos$txt$), $txt$Vicente Scavone & Cía / Scavone Hnos.$txt$, null, $txt$Grupo con presencia histórica en distribución farmacéutica.$txt$, null, 12),

((select id from market_independent_sections where rubro=$txt$Telecomunicaciones / logística$txt$), $txt$Tigo (Millicom)$txt$, null, $txt$Líder de mercado en telefonía móvil e internet.$txt$, 'gptw', 1),
((select id from market_independent_sections where rubro=$txt$Telecomunicaciones / logística$txt$), $txt$Claro Paraguay (América Móvil)$txt$, null, $txt$Segundo operador móvil; TecnoParaguay (Harrison) es su dealer.$txt$, null, 2),
((select id from market_independent_sections where rubro=$txt$Telecomunicaciones / logística$txt$), $txt$Vox (Copaco)$txt$, null, $txt$Operador estatal.$txt$, null, 3),
((select id from market_independent_sections where rubro=$txt$Telecomunicaciones / logística$txt$), $txt$Teisa Telecomunicaciones$txt$, null, $txt$Proveedor de infraestructura de telecomunicaciones.$txt$, 'gptw', 4),
((select id from market_independent_sections where rubro=$txt$Telecomunicaciones / logística$txt$), $txt$DHL Paraguay$txt$, null, $txt$Logística internacional — múltiple ganador consecutivo de GPTW Paraguay.$txt$, 'gptw', 5);

-- =========================================================================
-- market_share (5 filas)
-- =========================================================================
insert into market_share (rubro, grupo_label, empresa, valor, dato, fuente, sort_order) values
($txt$Hamburguesas congeladas$txt$, $txt$Grupo Pettengill$txt$, $txt$Frigorífico Guaraní$txt$, 80,
 $txt$Lidera la producción de hamburguesas y domina más del 80% del mercado paraguayo desde 2003.$txt$,
 $txt$InfoNegocios, entrevista a Luis Pettengill$txt$, 1),
($txt$Cemento$txt$, $txt$Grupo Bogarín$txt$, $txt$Yguazú Cementos$txt$, 40,
 $txt$Abastece cerca del 40% del consumo nacional de cemento.$txt$,
 $txt$Revista PLUS, 2020$txt$, 2),
($txt$Gaseosas (segmento económico)$txt$, $txt$Grupo Riquelme$txt$, $txt$EMCESA — Niko + De la Costa$txt$, 35,
 $txt$Participación de mercado reportada en el segmento de gaseosas de bajo precio.$txt$,
 $txt$Caso GeneXus (dato ~2014, a reconfirmar vigencia)$txt$, 3),
($txt$Seguros (primas directas)$txt$, $txt$Independiente$txt$, $txt$Mapfre Paraguay$txt$, 13.1,
 $txt$Motivo: fortaleza histórica en seguros de auto y salud, más 25+ años de marca instalada en Paraguay (desde 1998) — lidera primas directas con US$72,5M en el ejercicio 2024/2025.$txt$,
 $txt$Forbes Paraguay / La Nación, 2025$txt$, 4),
($txt$Seguros (utilidades)$txt$, $txt$Independiente$txt$, $txt$Itaú Seguros Paraguay$txt$, 28.17,
 $txt$Motivo: modelo de bancaseguros — se apalanca en la red de sucursales y clientes del Banco Itaú para vender pólizas con bajo costo de adquisición, lo que le da más rentabilidad que volumen de primas.$txt$,
 $txt$La Nación, ranking de utilidades 2025/2026$txt$, 5);

-- =========================================================================
-- market_scale (10 filas)
-- =========================================================================
insert into market_scale (rubro, grupo_label, empresa, dato, fuente, sort_order) values
($txt$Combustibles$txt$, $txt$Grupo Zapag$txt$, $txt$Copetrol + Nextar (ex-Petrobras)$txt$,
 $txt$Integra dos de las redes de distribución de combustibles más grandes del país tras la compra de los activos de Petrobras Paraguay.$txt$,
 $txt$Revista PLUS / ABC Color, 2019$txt$, 1),
($txt$Combustibles$txt$, $txt$Grupo Ortega$txt$, $txt$Barcos & Rodados$txt$,
 $txt$Red de aprox. 350–360 estaciones de servicio a nivel nacional, una de las mayores del país.$txt$,
 $txt$Prensa económica, 2021$txt$, 2),
($txt$Combustibles$txt$, $txt$Grupo Martín Martín$txt$, $txt$Fuelpar$txt$,
 $txt$Más de 78 estaciones de servicio, con fuerte presencia en la zona norte del país.$txt$,
 $txt$Sitio corporativo Fuelpar$txt$, 3),
($txt$Salud / diversificado$txt$, $txt$Grupo Harrison$txt$, $txt$Holding de 17 empresas (Robert y Aldo Harrison)$txt$,
 $txt$Facturación estimada de US$ 500 millones anuales según Forbes Paraguay.$txt$,
 $txt$Forbes Paraguay, 2025$txt$, 4),
($txt$Retail / bebidas$txt$, $txt$Grupo Vierci$txt$, $txt$BDP + Retail SA (Stock, Superseis)$txt$,
 $txt$Red combinada de más de 32.000 puntos de venta a nivel nacional tras la fusión con CCU.$txt$,
 $txt$Forbes Paraguay / La Nación, 2024$txt$, 5),
($txt$Farmacias (retail)$txt$, $txt$Independiente$txt$, $txt$Punto Farma$txt$,
 $txt$Motivo: lidera por escala de puntos de venta con 700+ sucursales — más del triple que Farmacenter (~200) y cinco veces FarmaOliva (140) — apalancado en 24 años de expansión desde su fundación (2001) y el concepto de 'farmacia ampliada' (salud + belleza + delivery).$txt$,
 $txt$Pharmabiz.NET / ViaParaguay$txt$, 6),
($txt$Combustibles$txt$, $txt$Independiente$txt$, $txt$Puma Energy$txt$,
 $txt$Motivo: entre los 5 primeros emblemas del país (~160 estaciones) gracias al respaldo del trader global Trafigura (dueño de la marca desde 1997) y terminales propias en San Antonio, Encarnación y Alto Paraná que le dan independencia logística frente a otros distribuidores.$txt$,
 $txt$Forbes Paraguay / sitio corporativo Puma Energy$txt$, 7),
($txt$Financiero / seguros$txt$, $txt$Grupo Cogorno$txt$, $txt$Interfisa Banco + Río Seguros$txt$,
 $txt$Motivo: tras tomar control mayoritario de Interfisa en 2020, el grupo usó esa plataforma bancaria para diversificarse a seguros comprando Río Seguros en 2025 — estrategia de cross-selling entre banca, retail (Shopping China) y mayorista (Fortis).$txt$,
 $txt$El Nacional / LexLatin, 2025$txt$, 8),
($txt$Snacks (papas fritas)$txt$, $txt$Grupo Vierci$txt$, $txt$PepsiCo Lay's (vía AV SA)$txt$,
 $txt$Motivo: exclusividad de distribución de AV SA (Vierci) con PepsiCo desde 2018, más una planta propia en construcción en San Antonio que reduce costos logísticos frente a importar — Lay's lidera la categoría de papas fritas del país.$txt$,
 $txt$InfoNegocios / Revista PLUS$txt$, 9),
($txt$Banca$txt$, $txt$Grupo Vierci$txt$, $txt$Banco GNB Paraguay (44%)$txt$,
 $txt$Motivo: escaló de 25,68% (2019, US$150M) a 44% (2023, +US$66M) porque el controlante colombiano Grupo Gilinski buscaba socios locales para fondear crecimiento sin ceder el control de la gestión — Vierci diversifica así su conglomerado hacia la banca.$txt$,
 $txt$Revista PLUS / La República, 2023$txt$, 10);

-- =========================================================================
-- Verificación rápida de conteos esperados (correr después de insertar):
-- select count(*) from market_groups;                    -- 17
-- select count(*) from market_companies;                 -- 124
-- select count(*) from market_independent_sections;      -- 24
-- select count(*) from market_independent_items;         -- 121
-- select count(*) from market_share;                     -- 5
-- select count(*) from market_scale;                     -- 10
-- =========================================================================
